### ISSUE TITLE
Маршруты без имён генерируют html-ошибку в конце тела ответа

### ISSUE THREAD

**Issue by roxblnfk** [phpdigest/api#5]
![image](https://user-images.githubusercontent.com/4152481/90336592-892aa680-dfe5-11ea-9b23-af9d3a6ac435.png)

Необходимо разобраться: косяк роутера или ещё чего?

**Comment by samdark** [comment]
А какое имя ты указываешь при генерации, если никакого не задал?

**Comment by roxblnfk** [comment]
> А какое имя ты указываешь при генерации, если никакого не задал?

никакой генерации

**Comment by samdark** [comment]
Но ошибка же "cannot generate".

**Comment by roxblnfk** [comment]
Вот страница, как пример
[test.txt](https://github.com/phpdigest/api/files/5081235/test.txt)
Похоже косячит роутер, вызываемый в дебагере

**Comment by samdark** [comment]
Отключи дебаггер. Если пропадёт, то да.

**Comment by roxblnfk** [comment]
а ещё заметил, что в выводе стека аргументы идут задом наперёд
![image](https://user-images.githubusercontent.com/4152481/90342026-85127f00-e00d-11ea-9ed4-56031948506c.png)

> Отключи дебаггер. Если пропадёт, то да.

Без дебага всё нормально
В имя безымянного маршрута подмешивается метод, получается "POST /user", и, видимо, это мешает найти маршрут в общем списке

**Comment by samdark** [comment]
Вероятно поломалось после https://github.com/yiisoft/router/commit/ab20eb175068f5d5bd8e213a52b320ad418946fa

**Comment by samdark** [comment]
> а ещё заметил, что в выводе стека аргументы идут задом наперёд

Гы :)

**Comment by samdark** [comment]
На тему error handler: https://github.com/yiisoft/yii-web/pull/303

**Comment by samdark** [comment]
Ошибку на тему генерации URL не воспроизвёл на чистом yiisoft/app.

**Comment by roxblnfk** [comment]
> Ошибку на тему генерации URL не воспроизвёл на чистом yiisoft/app.

попробуй убрать вывод заголовка Content-Length или используй стрим без известной длины тела ответа. Либо закомментируй `emit()`

**Comment by roxblnfk** [comment]
Fixed https://github.com/yiisoft/router/pull/61
